language: java
sudo: false # faster builds

addons:
  sonarcloud:
    organization: "parsingdata"
    projectKey: "parsingdata_metal"

jdk:
  - oraclejdk8
  - oraclejdk9

before_install: pip install --user codecov

script: mvn clean verify sonar:sonar

after_success: codecov
